### ISSUE TITLE
Support for .floss flow files 

### ISSUE THREAD

**Issue by yyeboah** [georgegach/flowiz#13]
Firstly, I have found this library pretty useful in the past and I would like to express gratitude to the contributors for putting this out there.

I have however recently encountered .floss files and it appears that these formats are currently not supported ? Is there any support I may not be aware of, or a recommended way to convert between .floss and .flo formats so that the current library could be used as-is?

**Comment by georgegach** [comment]
Thanks! It is my pleasure that people actually found this tiny project I made for my thesis useful.

`.flo` has been an industry standard for a very long time due to the influence of this project: https://vision.middlebury.edu/flow/. 

Unfortunately, I no longer work in the field and hence haven't really kept track of the rise of new file formats to help you out right away. However, I'm certainly interested to check it out sometime. Could you point me to the source or a popular foss project where this file format is being used?

**Comment by yyeboah** [comment]
Thanks for the useful response. It does indeed appear that .flow is the widely accepted standard even as at now and I find it 
 sound and straight-forward to simply stick with .flow.

Having said that, happy to keep using the library as-as. Cheers.
